# Site settings
author: DJ Taylor
title: Adventures in Coding
header-img: img/home-bg.png
email: dtaylor88@gmail.com
copyright_name: DJ Taylor
description: > # this means to ignore newlines until "baseurl:"
  My journey as a budding software engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  djtaylor8

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
